### PR TITLE
Feature/refactor css

### PR DESCRIPTION
**Pull request by jheidepriem**
# Description

Refactored CSS and HTML. Created loose template for JS.

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Review by BobAiken — APPROVED** [review]
Thanks for organizing all that! This will definitely help us moving forward to keep our code readable and DRY.

**Review by BHaddad1 — APPROVED** [review]
The refactoring and alphabetical listing of the CSS rules looks great!

**Review by RyanBaer42 — APPROVED** [review]
Thank you for restructuring the CSS, it's much easier to navigate through the file now. Also the indentation looks much better on the HTML file now.

**Comment by BHaddad1** [comment]
Thanks Josephine! The CSS is much more organized, and the HTML looks a lot cleaner.

**Pull request merged**
