### PR TITLE
Feature initial css

### PR DESCRIPTION
**Pull request by RyanBaer42**
# Description

Updated HTML to include additional class names, added divs and sections to separate out parts of the additional HTML, added a grid to the "new-ideas" section. Added css stylings for each section, button, and input area. Included stylings for the new-idea-boxes that will be added through innerHTML later. 

# How Has This Been Tested?

User app tested

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by BHaddad1 — DISMISSED** [review]
I think these changes are excellent, we will just need to clean up our CSS doc. The new HTML looks good.

**Comment by BHaddad1** [comment]
The HTML and CSS looks good. The grid is necessary, and looks good. The CSS doc is going to be okay. Josephine will work on alphabetizing that!

**Review by jheidepriem — APPROVED** [review]
Looks great. I will refactor css and push changes in the next 24 hours.

**Review by BHaddad1 — APPROVED** [review]
The HTML and CSS looks good. Josephine will take care of the CSS alphabetizing. Thank you for adding the images to the assets folder!

**Review by BobAiken — APPROVED** [review]
The CSS and HTML look good. Thanks for adding the assets folder.

**Comment by BHaddad1** [comment]
Thanks everyone for approving! Please git fetch and git pull!

**Pull request merged**
